import { useState, type FormEvent } from "react";
import { BarChart3, Heart, MapPin, Menu, Search, ShoppingCart, UserRound, X } from "lucide-react";
import { Link, NavLink, Outlet, useNavigate } from "react-router-dom";
import { categoriesApi } from "../api/categories.api";
import { extractApiError } from "../api/client";
import { useAuth, useCart, useCity, useLanguage, useSaved } from "../contexts/AppContexts";
import { ErrorMessage, LoadingSpinner, useApiResource } from "../components/common/States";
import { formatPrice } from "../utils/format";

export function MainLayout() {
  const navigate = useNavigate(); const [query, setQuery] = useState(""); const [open, setOpen] = useState(false); const [changingCity, setChangingCity] = useState(false); const [notice, setNotice] = useState("");
  const cityContext = useCity(); const { city, cities, setCity } = cityContext; const { language, setLanguage } = useLanguage(); const cartContext = useCart(); const { cart } = cartContext; const saved = useSaved(); const auth = useAuth();
  const categories = useApiResource(() => categoriesApi.tree(), [language]);
  const submit = (event: FormEvent) => { event.preventDefault(); if (query.trim()) { setOpen(false); navigate(`/search?q=${encodeURIComponent(query.trim())}`); } };
  const selectCity = async (slug: string) => { setChangingCity(true); setNotice(""); try { await setCity(slug); } catch (reason) { setNotice(extractApiError(reason)); } finally { setChangingCity(false); } };
  const contextErrors = [...new Set([cityContext.error, cartContext.error, saved.error, auth.error].filter(Boolean))];
  return <><header className="site-header"><div className="top-strip"><div className="shell top-inner"><label className="city-picker"><MapPin size={14}/><span className="sr-only">Қала</span><select aria-label="Қала" value={city} disabled={cityContext.loading || changingCity} onChange={(event) => void selectCity(event.target.value)}>{!cities.length && <option value={city}>{cityContext.loading ? "Жүктелуде…" : city}</option>}{cities.map((item) => <option key={item.id} value={item.slug}>{item.name}</option>)}</select></label><div className="top-links"><Link to="/delivery-and-payment">Жеткізу және төлем</Link><Link to="/contacts">Дүкендер</Link><Link to="/faq">Көмек</Link><button className="language" aria-label="Тілді ауыстыру" onClick={() => setLanguage(language === "kk" ? "ru" : "kk")}>{language === "kk" ? "ҚАЗ" : "РУС"}</button></div></div></div>
    <div className="shell main-header"><Link className="logo" to="/">EKT<span>.KZ</span></Link><button className="catalog-trigger" onClick={() => setOpen(!open)} aria-expanded={open}><Menu size={19}/>Каталог</button><form className="search-form" onSubmit={submit}><Search size={20}/><input aria-label="Тауар іздеу" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Тауарды, брендті немесе артикулды іздеу"/><button type="submit">Іздеу</button></form>
      <nav className="header-actions" aria-label="Пайдаланушы әрекеттері"><Link to="/compare" aria-label="Салыстыру"><BarChart3/><small>{saved.comparison.length}</small></Link><Link to="/favorites" aria-label="Таңдаулылар"><Heart/><small>{saved.favorites.length}</small></Link><Link to={auth.user ? "/account" : "/login"} aria-label="Жеке кабинет"><UserRound/></Link><Link className="cart-link" to="/cart"><ShoppingCart/><span><b>{cart?.totalItemCount ?? 0} тауар</b><small>{formatPrice(cart?.subtotal ?? 0)}</small></span></Link></nav>
    </div>
    {open && <div className="mega-menu"><div className="shell"><div className="mega-heading"><b>Тауарлар каталогы</b><button aria-label="Жабу" onClick={() => setOpen(false)}><X size={18}/></button></div>{categories.loading ? <LoadingSpinner/> : categories.error ? <ErrorMessage message={categories.error} retry={categories.reload}/> : <div className="category-menu">{categories.data?.map((category) => <div className="category-menu-group" key={category.id}><Link onClick={() => setOpen(false)} to={`/catalog/${category.slug}`}>{category.name}<span>›</span></Link>{category.children?.map((child) => <Link className="subcategory-menu-link" key={child.id} onClick={() => setOpen(false)} to={`/catalog/${child.slug}`}>{child.name}</Link>)}</div>)}</div>}<p className="image-search-note"><button className="text-button" onClick={() => { setNotice("Сурет бойынша іздеу әлі бапталмаған. Тауар атауы немесе артикул арқылы іздеңіз."); setOpen(false); }}>Сурет бойынша іздеу</button></p></div></div>}
  </header>
    <main className="shell">{notice && <div className="notice" role="status"><p>{notice}</p><button className="text-button" onClick={() => setNotice("")} aria-label="Хабарламаны жабу">Жабу</button></div>}{contextErrors.map((error) => <ErrorMessage key={error} message={error}/>)}<Outlet/></main>
    <nav className="mobile-nav"><NavLink to="/catalog"><Menu/>Каталог</NavLink><NavLink to="/favorites"><Heart/>Таңдаулы</NavLink><NavLink to="/cart"><ShoppingCart/>Себет</NavLink><NavLink to="/account"><UserRound/>Кабинет</NavLink></nav>
    <footer className="site-footer"><div className="shell footer-grid"><div><Link className="logo" to="/">EKT<span>.KZ</span></Link><p>Электр жабдықтарының демо дүкені.</p></div><div><b>Сатып алушыға</b><Link to="/delivery-and-payment">Жеткізу және төлем</Link><Link to="/returns-and-exchange">Қайтару және айырбастау</Link><Link to="/how-to-order">Қалай тапсырыс беру керек</Link><Link to="/online-payment">Онлайн төлем</Link><Link to="/installment">Бөліп төлеу</Link></div><div><b>Компания</b><Link to="/contacts">Байланыстар</Link><Link to="/news">Жаңалықтар</Link><Link to="/b2b">Заңды тұлғаларға</Link><Link to="/privacy-policy">Құпиялық саясаты</Link></div><div><b>Көмек</b><Link to="/faq">Жиі қойылатын сұрақтар</Link><Link to="/contacts">Өтінім жіберу</Link><span>Контактілер таңдалған қала бойынша көрсетіледі.</span></div></div></footer>
  </>;
}
