import { createContext, useContext, useEffect, useState, type PropsWithChildren } from "react";
import { authApi } from "../api/auth.api"; import { cartApi } from "../api/cart.api"; import { citiesApi } from "../api/cities.api"; import { comparisonApi } from "../api/comparison.api"; import { favoritesApi } from "../api/favorites.api";
import type { AuthUser, LoginPayload, RegisterPayload } from "../types/auth.types"; import type { Cart } from "../types/cart.types"; import type { City } from "../types/city.types"; import type { Product } from "../types/product.types"; import { readStorage, storageKeys, writeStorage } from "../utils/storage";
type Language = "kk" | "ru"; type CartValue = { cart: Cart | null; refresh: () => Promise<void>; add: (id: string, q: number) => Promise<void>; update: (id: string, q: number) => Promise<void>; remove: (id: string) => Promise<void>; clear: () => Promise<void> };
const LanguageContext = createContext<{ language: Language; setLanguage: (v: Language) => void } | null>(null); const CityContext = createContext<{ city: string; cities: City[]; setCity: (v: string) => void } | null>(null); const AuthContext = createContext<{ user: AuthUser | null; login: (v: LoginPayload) => Promise<void>; register: (v: RegisterPayload) => Promise<void>; logout: () => void } | null>(null); const CartContext = createContext<CartValue | null>(null); const SavedContext = createContext<{ favorites: Product[]; comparison: Product[]; toggleFavorite: (p: Product) => Promise<void>; toggleCompare: (p: Product) => Promise<void>; clearCompare: () => Promise<void> } | null>(null);
export function AppProviders({ children }: PropsWithChildren) { const [language, setLanguageState] = useState<Language>((readStorage(storageKeys.language) as Language | null) ?? "kk"); const [city, setCityState] = useState(readStorage(storageKeys.city) ?? "almaty"); const [cities, setCities] = useState<City[]>([]); const [user, setUser] = useState<AuthUser | null>(null); const [cart, setCart] = useState<Cart | null>(null); const [favorites, setFavorites] = useState<Product[]>([]); const [comparison, setComparison] = useState<Product[]>([]);
 const refresh = async () => setCart(await cartApi.get()); const refreshSaved = async () => { setFavorites(await favoritesApi.list()); setComparison(await comparisonApi.list()); }; useEffect(() => { void citiesApi.list().then(setCities); void refresh(); void refreshSaved(); const token = readStorage(storageKeys.token); if (token) void authApi.me().then(setUser).catch(() => writeStorage(storageKeys.token, "")); }, []);
 const setCity = (v: string) => { writeStorage(storageKeys.city, v); setCityState(v); void cartApi.setCity(v).then(setCart); }; const setLanguage = (v: Language) => { writeStorage(storageKeys.language, v); setLanguageState(v); };
 const cartValue: CartValue = { cart, refresh, add: async (id, q) => setCart(await cartApi.addItem({ productId: id, quantity: q })), update: async (id, q) => setCart(await cartApi.updateItem(id, q)), remove: async (id) => setCart(await cartApi.removeItem(id)), clear: async () => setCart(await cartApi.clear()) };
 const saved = { favorites, comparison, toggleFavorite: async (p: Product) => { if (favorites.some((x) => x.id === p.id)) await favoritesApi.remove(p.id); else await favoritesApi.add(p.id); await refreshSaved(); }, toggleCompare: async (p: Product) => { if (comparison.some((x) => x.id === p.id)) await comparisonApi.remove(p.id); else await comparisonApi.add(p.id); await refreshSaved(); }, clearCompare: async () => { await comparisonApi.clear(); await refreshSaved(); } };
 const auth = { user, login: async (v: LoginPayload) => { const s = await authApi.login(v); writeStorage(storageKeys.token, s.token); setUser(s.user); }, register: async (v: RegisterPayload) => { const s = await authApi.register(v); writeStorage(storageKeys.token, s.token); setUser(s.user); }, logout: () => { writeStorage(storageKeys.token, ""); setUser(null); } };
 return <LanguageContext.Provider value={{ language, setLanguage }}><CityContext.Provider value={{ city, cities, setCity }}><AuthContext.Provider value={auth}><CartContext.Provider value={cartValue}><SavedContext.Provider value={saved}>{children}</SavedContext.Provider></CartContext.Provider></AuthContext.Provider></CityContext.Provider></LanguageContext.Provider>; }
function required<T>(value: T | null, name: string) { if (!value) throw new Error(`${name} missing`); return value; } export const useLanguage = () => required(useContext(LanguageContext), "LanguageContext"); export const useCity = () => required(useContext(CityContext), "CityContext"); export const useAuth = () => required(useContext(AuthContext), "AuthContext"); export const useCart = () => required(useContext(CartContext), "CartContext"); export const useSaved = () => required(useContext(SavedContext), "SavedContext");
